name: flutter_travis_sample

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - name: install dependecies
        run: flutter packages get
      - name: run tests
        run: flutter test --exclude-tags='no-ci'